travis:
  secure:
    BINSTAR_TOKEN: y63EWXqcbfBd9xMv0jjSzKuq+bSsuRkmJ5IUF8obpZ2thEXDQznNTWZspnf8v+4qj/NvN2+81py6qfuJeoH38PftAdcavHcwAJertkFzf55/q8aNy9V1MYvJCEekO6CDwSRhJERa95lBu7nixXRogI80fRr5F1fYLnDZzhBROZuS7UmNlyYy4a0c5oK4jbSkpIIdu52a4czDyzmadhDb3GTB7P+DaURuiR50kR7uI+so+dB0Ja40SevvRRkMIzoQyHyjwTNP5wJ5+XcizxhNzeMTOa1MoeMPKRGMyJV5L9xYROINq1QPuwo0x5kYB7bCBd6cE5vRWwq/ZKoI1B6oyBe5dkwKCfAEMxgnsMW7lgoiGaZyIZ0E1ZQQnSgRgnJKrEM6BqqpwIDnFBMCx1GYnTUJLJwULeYN0NV+mxGZqh7DoVIyEdvUCV1G4bOqgXZhar3Jtq9Fd8iB4SFVatkMvDOjLZZuFb1wg0/C1RBo+c+dnchqCBbNAHX1sva7e+WFYIsjySKX7jlIHus63TYVv/PW2OG0mtpMA9jK/ZmsDIsJt9mIWLM+7bFSHLOFpCkhRrj4V8F294n/t9oLBj/E/eTgIsNMZCMcO5+xaDFSJ9gKvCQQ3L/li5poVWawylbrM5f49c1A8PVuWInC+1flh0epyXywCuhKbUU0Yhv2SNQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
