travis:
  secure:
    BINSTAR_TOKEN: PCHWLz+UZCnBjIcd7n0GQYmd0Ic4Gyq/DQTDO604Fye2MoIy4LtD4FcZpFXFkNvvGewIm6hQQ9eDu8XSVRWjyQojTjjN97K1PNYP7AK6aqqHZOa2w1MryKhFuO1mtOQjawGyKSuLMHv+XXgBhm3f0rW0XE9UhCxW6RMAtshM3LQ93jvnk1LsGbCjVldyaU0Lyuw/Ik0+ccOH2Gp5r49CoJrAzcONNgdvFBaW8UQ4oY6hjthXBEhby80NCNIBt8FRvN7eMuv8+Kh3F3vmNhGgrh6EbYU1oxH16T2DnG37oM9Sc6OcvT9BVVMoqwFMK0FQInb24ieI9+U+Q1RYg0ivgRz/zagW8z/K/spm1/h7eaah9Sx105bqfBHKanJMa4zIBxbVZ/l30+VuSun2ypmbH/R5gIXGBU8R3xp3NxoMOo1+LCbph/VkYNcPZzkXb/8fe+tjkfs1Xf+PKFtXTX13xrdPOt/Scne9oTda4iGdRpXpKeC7Pg3FuTnWlg7U8HpRWxLG6TH2mJhX0L1y+OA3HYM85/WFZX0Z+mWwmhfv/lNOISSv3qdyy3hz8NRFL4rYuKR7eqdf0eQG8X5vIEVjFNWuRLlk3J4aQ+h+UR2/vDTn+4KOjNu/EynPdlCK11vU7Ih48ugRBp59By9LyAdww8/oo7u9vOQGa+tot0Q/SfQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
